looking_for_an_a: looking_for_an_a.o
	g++ looking_for_an_a.cc -o looking_for_an_a

looking_for_an_a.o: looking_for_an_a.cc
	g++ -c looking_for_an_a.cc -o looking_for_an_a.o

clean:
	rm -rf *.o 
	rm looking_for_an_a