divisors_in_order: divisors_in_order.o
	g++ divisors_in_order.cc -o divisors_in_order

divisors_in_order.o: divisors_in_order.cc
	g++ -c divisors_in_order.cc -o divisors_in_order.o

clean:
	rm -rf *.o 
	rm divisors_in_order