harmonic_numbers_II: harmonic_numbers_II.o
	g++ harmonic_numbers_II.cc -o harmonic_numbers_II

harmonic_numbers_II.o: harmonic_numbers_II.cc
	g++ -c harmonic_numbers_II.cc -o harmonic_numbers_II.o

clean:
	rm -rf *.o 
	rm harmonic_numbers_II