approximation_of_e: approximation_of_e.o
	g++ approximation_of_e.cc -o approximation_of_e

approximation_of_e.o: approximation_of_e.cc
	g++ -c approximation_of_e.cc -o approximation_of_e.o

clean:
	rm -rf *.o 
	rm approximation_of_e