first_position_of_even: first_position_of_even.o
	g++ first_position_of_even.cc -o first_position_of_even

first_position_of_even.o: first_position_of_even.cc
	g++ -c first_position_of_even.cc -o first_position_of_even.o

clean:
	rm -rf *.o 
	rm first_position_of_even