harmonic_numbers: harmonic_numbers.o
	g++ harmonic_numbers.cc -o harmonic_numbers

harmonic_numbers.o: harmonic_numbers.cc
	g++ -c harmonic_numbers.cc -o harmonic_numbers.o

clean:
	rm -rf *.o 
	rm harmonic_numbers